---
ID: "0e7ec55e-1063-41db-af7d-6d3e4e639c12"
Parent: "d0328bbc-0812-439e-ad28-6022697420c9"
Template: "d0328bbc-0812-439e-ad28-6022697420c9"
Path: /sitecore/templates/Project/Page Content/Components/Rendering Parameters/Tab Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230621T214109Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dean.draper@arkanedigital.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dean.draper@arkanedigital.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e489dd07-a568-4da1-bdaf-eb56a5aa4d66"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230628T221952Z
