---
ID: "ad3c8b2e-b8fc-4c14-84fc-a045ee78a89c"
Parent: "cdf9c727-2597-4478-aa05-273814ee6b5a"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: /sitecore/content/Compassion/Compassion/Compassion Campaigns/Settings/Shared Sites Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230627T182754Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fc896f43-46f3-442c-b3c6-665db1694a5a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230627T182754Z
